version: "3.5"
services:
  sut:
    image: testeditor/angular-sut:snapshot
    ports:
      - "4300:4200"
  gitrepo:
    image: testeditor/git-examples:snapshot
    ports:
      - "2222:22"
    healthcheck:
      test: ["CMD-SHELL", "/git-server/healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
  persistence:
    image: testeditor/persistence:snapshot
    ports:
      - "9080:8080"
    environment:
      KNOWN_HOSTS_CONTENT: "$KNOWN_HOSTS_CONTENT"
      ADD_KNOWN_HOSTS_DOMAIN: "gitrepo:22"
      GIT_PRIVATE_KEY: "$GIT_PRIVATE_KEY"
      TARGET_REPO: "ssh://git@gitrepo:22/git-server/repos/language-examples.git"
      BRANCH_NAME: "feature/r2d2"
      TIMEZONE: Europe/Berlin
    depends_on:
      - gitrepo
      - sut
  xtext:
    image: testeditor/xtext:snapshot
    ports:
      - "8080:8080"
    environment:
      ADD_KNOWN_HOSTS_DOMAIN: "gitrepo:22"
      GIT_PRIVATE_KEY: "$GIT_PRIVATE_KEY"
      TARGET_REPO: "ssh://git@gitrepo:22/git-server/repos/language-examples.git"
      BRANCH_NAME: "feature/r2d2"
      TIMEZONE: Europe/Berlin
    depends_on:
      - gitrepo
    command: [ "./wait-for-it.sh", "gitrepo:22", "--", "./run.ssh" ]
  web:
    image: testeditor/web:snapshot
    ports:
      - "4200:4200"
    depends_on:
      - persistence
      - xtext
